
# the storage space of result files
data:
    save_loc: '/glade/derecho/scratch/ksha/CREDIT/verif/PLOT_data/'

# Matplotlib figure export settings
figure:
    save_loc: '/glade/u/home/ksha/figures/'
    keys:
        dpi: 250
        orientation: 'portrait' 
        bbox_inches: 'tight' 
        pad_inches: 0.1 
        transparent: False
