qsub:
    qsub_loc: '/glade/u/home/ksha/credit-data/qsub/'
    scripts_loc: '/glade/u/home/ksha/credit-data/data_preprocessing/scripts/'


zscore:
    U:    '/glade/derecho/scratch/schreck/STAGING/TOTAL_*'
    V:    '/glade/derecho/scratch/schreck/STAGING/TOTAL_*'
    T:    '/glade/derecho/scratch/schreck/STAGING/TOTAL_*'
    Q:    '/glade/derecho/scratch/schreck/STAGING/TOTAL_*'
    SP:   '/glade/derecho/scratch/schreck/STAGING/TOTAL_*'
    t2m:  '/glade/derecho/scratch/schreck/STAGING/TOTAL_*'
    V500: '/glade/derecho/scratch/schreck/STAGING/TOTAL_*'
    U500: '/glade/derecho/scratch/schreck/STAGING/TOTAL_*'
    T500: '/glade/derecho/scratch/schreck/STAGING/TOTAL_*'
    Z500: '/glade/derecho/scratch/schreck/STAGING/TOTAL_*'
    Q500: '/glade/derecho/scratch/schreck/STAGING/TOTAL_*'
    tsi:  '/glade/derecho/scratch/dgagne/credit_solar_1h_0.25deg/*.nc'
    save_loc: '/glade/campaign/cisl/aiml/ksha/CREDIT/'
    years_range: [1979, 2014]
    prefix: '1h'
    
